export const ADMIN_GET_DRESSES_REQUEST = "ADMIN_GET_DRESSES_REQUEST";
export const ADMIN_GET_DRESSES_SUCCESS = "ADMIN_GET_DRESSES_SUCCESS";
export const ADMIN_GET_DRESSES_FAILURE = "ADMIN_GET_DRESSES_FAILURE";

export const ADMIN_ADD_DRESSES_REQUEST = "ADMIN_ADD_DRESSES_REQUEST";
export const ADMIN_ADD_DRESSES_SUCCESS = "ADMIN_ADD_DRESSES_SUCCESS";
export const ADMIN_ADD_DRESSES_FAILURE = "ADMIN_ADD_DRESSES_FAILURE";

export const ADMIN_UPDATE_DRESSES_REQUEST = "ADMIN_UPDATE_DRESSES_REQUEST";
export const ADMIN_UPDATE_DRESSES_SUCCESS = "ADMIN_UPDATE_DRESSES_SUCCESS";
export const ADMIN_UPDATE_DRESSES_FAILURE = "ADMIN_UPDATE_DRESSES_FAILURE";

export const ADMIN_DELETE_DRESSES_REQUEST = "ADMIN_DELETE_DRESSES_REQUEST";
export const ADMIN_DELETE_DRESSES_SUCCESS = "ADMIN_DELETE_DRESSES_SUCCESS";
export const ADMIN_DELETE_DRESSES_FAILURE = "ADMIN_DELETE_DRESSES_FAILURE";

export const ADMIN_SINGLE_DRESSES_REQUEST = "ADMIN_SINGLE_DRESSES_REQUEST";
export const ADMIN_SINGLE_DRESSES_SUCCESS = "ADMIN_SINGLE_DRESSES_SUCCESS";
export const ADMIN_SINGLE_DRESSES_FAILURE = "ADMIN_SINGLE_DRESSES_FAILURE";