export const ADMIN_GET_DRESS_REQUEST = "ADMIN_GET_DRESS_REQUEST";
export const ADMIN_GET_DRESS_SUCCESS = "ADMIN_GET_DRESS_SUCCESS";
export const ADMIN_GET_DRESS_FAILURE = "ADMIN_GET_DRESS_FAILURE";

export const ADMIN_ADD_DRESS_REQUEST = "ADMIN_ADD_DRESS_REQUEST";
export const ADMIN_ADD_DRESS_SUCCESS = "ADMIN_ADD_DRESS_SUCCESS";
export const ADMIN_ADD_DRESS_FAILURE = "ADMIN_ADD_DRESS_FAILURE";

export const ADMIN_UPDATE_DRESS_REQUEST = "ADMIN_UPDATE_DRESS_REQUEST";
export const ADMIN_UPDATE_DRESS_SUCCESS = "ADMIN_UPDATE_DRESS_SUCCESS";
export const ADMIN_UPDATE_DRESS_FAILURE = "ADMIN_UPDATE_DRESS_FAILURE";

export const ADMIN_DELETE_DRESS_REQUEST = "ADMIN_DELETE_DRESS_REQUEST";
export const ADMIN_DELETE_DRESS_SUCCESS = "ADMIN_DELETE_DRESS_SUCCESS";
export const ADMIN_DELETE_DRESS_FAILURE = "ADMIN_DELETE_DRESS_FAILURE";

export const ADMIN_SINGLE_DRESS_REQUEST = "ADMIN_SINGLE_DRESS_REQUEST";
export const ADMIN_SINGLE_DRESS_SUCCESS = "ADMIN_SINGLE_DRESS_SUCCESS";
export const ADMIN_SINGLE_DRESS_FAILURE = "ADMIN_SINGLE_DRESS_FAILURE";