export const ADMIN_GET_FURNITURE_REQUEST = "ADMIN_GET_FURNITURE_REQUEST";
export const ADMIN_GET_FURNITURE_SUCCESS = "ADMIN_GET_FURNITURE_SUCCESS";
export const ADMIN_GET_FURNITURE_FAILURE = "ADMIN_GET_FURNITURE_FAILURE";

export const GET_FURNITURE_REQUEST = "GET_FURNITURE_REQUEST";
export const GET_FURNITURE_SUCCESS = "GET_FURNITURE_SUCCESS";
export const GET_FURNITURE_FAILURE = "GET_FURNITURE_FAILURE";

export const ADMIN_ADD_FURNITURE_REQUEST = "ADMIN_ADD_FURNITURE_REQUEST";
export const ADMIN_ADD_FURNITURE_SUCCESS = "ADMIN_ADD_FURNITURE_SUCCESS";
export const ADMIN_ADD_FURNITURE_FAILURE = "ADMIN_ADD_FURNITURE_FAILURE";

export const ADMIN_UPDATE_FURNITURE_REQUEST = "ADMIN_UPDATE_FURNITURE_REQUEST";
export const ADMIN_UPDATE_FURNITURE_SUCCESS = "ADMIN_UPDATE_FURNITURE_SUCCESS";
export const ADMIN_UPDATE_FURNITURE_FAILURE = "ADMIN_UPDATE_FURNITURE_FAILURE";

export const ADMIN_DELETE_FURNITURE_REQUEST = "ADMIN_DELETE_FURNITURE_REQUEST";
export const ADMIN_DELETE_FURNITURE_SUCCESS = "ADMIN_DELETE_FURNITURE_SUCCESS";
export const ADMIN_DELETE_FURNITURE_FAILURE = "ADMIN_DELETE_FURNITURE_FAILURE";

export const ADMIN_SINGLE_FURNITURE_REQUEST = "ADMIN_SINGLE_FURNITURE_REQUEST";
export const ADMIN_SINGLE_FURNITURE_SUCCESS = "ADMIN_SINGLE_FURNITURE_SUCCESS";
export const ADMIN_SINGLE_FURNITURE_FAILURE = "ADMIN_SINGLE_FURNITURE_FAILURE";