export const GET_DRESS_REQUEST = "GET_DRESS_REQUEST";
export const GET_DRESS_SUCCESS = "GET_DRESS_SUCCESS";
export const GET_DRESS_FAILURE = "GET_DRESS_FAILURE";



export const POST_DRESS_REQUEST = "POST_DRESS_REQUEST";
export const POST_DRESS_SUCCESS = "POST_DRESS_SUCCESS";
export const POST_DRESS_FAILURE = "POST_DRESS_FAILURE";